### ISSUE TITLE
Creazione file "checkstyle.xml"

### ISSUE THREAD

**Issue by UraganoAngelina** [jacopo-angeli/II-assignment-Angeli-Angeloni#13]

**Comment by jacopo-angeli** [comment]
Moduli richiesti:

- BooleanExpressionComplexity
- CyclomaticComplexity
- FileLength
- LineLength
- MethodLength
- EmptyCatchBlock
- FileTabCharacter
- AvoidStarImport
- IllegalImport
- NeedBraces
- Header con il seguente valore
```
////////////////////////////////////////////////////////////////////
// ALBERTO ANGELONI 1231122
// JACOPO ANGELI 1232583
////////////////////////////////////////////////////////////////////
```
Configurare il plugin in modo da far fallire la build se non vengono rispettati i controlli configurati.
